### ISSUE TITLE
TypeError: fns.shift(...) is not a function

### ISSUE THREAD

**Issue by phillmac** [alanshaw/it-pipe#1]
Not sure if this is the right spot for this issue, perhaps the problem is really in libp2p
js-ipfs version: 0.43.3

stacktrace:
```
/workspace/js-ipfs-orbit-db/node_modules/it-pipe/index.js:4
    res = fns.shift()(res)
                     ^

TypeError: fns.shift(...) is not a function
    at rawPipe (/workspace/js-ipfs-orbit-db/node_modules/it-pipe/index.js:4:22)
    at pipe (/workspace/js-ipfs-orbit-db/node_modules/it-pipe/index.js:49:10)
    at handleHop (/workspace/js-ipfs-orbit-db/node_modules/libp2p/src/circuit/circuit/hop.js:82:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ClassIsWrapper._onProtocol (/workspace/js-ipfs-orbit-db/node_modules/libp2p/src/circuit/index.js:53:29)
```

**Comment by alanshaw** [comment]
Almost certainly not an issue for this library. Is very likely that `hop.js` in libp2p/circuit is piping a null stream. It looks like https://github.com/libp2p/js-libp2p/blob/master/src/circuit/circuit/stop.js#L64-L68 doesn't always return something so this may be the cause.
